#!/usr/bin/env python3
"""Noto Sans JP（400・japanese サブセット）を Fontsource から取得し自前ホスト用 CSS を生成する。"""

from __future__ import annotations

import sys
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
FONT_VERSION = "5.2.5"
FONT_FILE = "japanese-400-normal.woff2"
FONT_URL = (
    f"https://cdn.jsdelivr.net/fontsource/fonts/noto-sans-jp@{FONT_VERSION}/{FONT_FILE}"
)
OUT_DIR = ROOT / "static" / "vendor" / "noto-sans-jp"
OUT_FONT = OUT_DIR / FONT_FILE
OUT_CSS = ROOT / "static" / "css" / "noto-sans-jp.css"
WEBFONT_PATH = "../vendor/noto-sans-jp/japanese-400-normal.woff2"

CSS_TEMPLATE = """\
/* Auto-generated by scripts/build_noto_sans_jp.py — do not edit by hand */
@font-face {{
  font-family: "Noto Sans JP";
  font-style: normal;
  font-display: swap;
  font-weight: 400;
  src: url({webfont}) format("woff2");
}}
"""


def _download_font() -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    if OUT_FONT.is_file() and OUT_FONT.stat().st_size > 100_000:
        print(f"Font exists: {OUT_FONT} ({OUT_FONT.stat().st_size} bytes)")
        return
    print(f"Downloading {FONT_URL} ...")
    try:
        with urllib.request.urlopen(FONT_URL, timeout=120) as resp:
            data = resp.read()
    except Exception as urllib_err:
        import subprocess

        print(f"urllib failed ({urllib_err}); trying curl ...")
        subprocess.run(
            ["curl", "-fsSL", "-o", str(OUT_FONT), FONT_URL],
            check=True,
            timeout=180,
        )
        print(f"Wrote {OUT_FONT} ({OUT_FONT.stat().st_size} bytes)")
        return
    OUT_FONT.write_bytes(data)
    print(f"Wrote {OUT_FONT} ({len(data)} bytes)")


def _write_css() -> None:
    css = CSS_TEMPLATE.format(webfont=WEBFONT_PATH)
    OUT_CSS.write_text(css, encoding="utf-8")
    print(f"Wrote {OUT_CSS} ({len(css)} bytes)")


def build() -> None:
    _download_font()
    _write_css()


if __name__ == "__main__":
    try:
        build()
    except Exception as exc:
        print(f"build_noto_sans_jp failed: {exc}", file=sys.stderr)
        sys.exit(1)
